### PR TITLE
Only build master branch

### PR DESCRIPTION
**Pull request by honnix**
# TL;DR
Only build on PR branch, not pushed-to branch.

## Type
 - [x] Bug Fix
 - [ ] Feature
 - [ ] Plugin

## Are all requirements met?

 - [ ] Code completed
 - [ ] Smoke tested
 - [ ] Unit tests added
 - [ ] Code documentation added
 - [ ] Any pending items have an associated Issue

## Complete description
Note sure this is intended configuration, but if not it should only build on PR branch, not pushed-to branch.

Reference: https://docs.travis-ci.com/user/web-ui/#build-pushed-branches

## Tracking Issue
https://github.com/lyft/flyte/issues/669

## Follow-up issue
_NA_

### CODE REVIEW

**Review by wild-endeavor — APPROVED** [review]
can merge this after.

**Comment by honnix** [comment]
@wild-endeavor After what?

**Comment by honnix** [comment]
After reading your comment in #332 , I guess you meant after merging `annotations` to `master`. Sure. Let's wait.

**Comment by honnix** [comment]
Close in favor of #337

**Pull request closed without merging**
