### PR TITLE
Add Python3.8 to TravisCI and no Python27

### PR DESCRIPTION
**Pull request by honnix**
# TL;DR
Add Python3.8 to TravisCI and stop supporting Python27.

## Type
 - [x] Bug Fix
 - [ ] Feature
 - [ ] Plugin

## Are all requirements met?

 - [x] Code completed
 - [ ] Smoke tested
 - [ ] Unit tests added
 - [ ] Code documentation added
 - [ ] Any pending items have an associated Issue

## Complete description
Add Python 3.8 as a job in TravisCI.

## Tracking Issue
https://github.com/lyft/flyte/issues/534

## Follow-up issue
N/A

### CODE REVIEW

**Comment by honnix** [comment]
Hmm, it turns out the last 2.x release of pyspark doesn't support Python 3.8. :( Any plan to upgrade pyspark to 3.x?

**Comment by wild-endeavor** [comment]
@akhurana001 ?

**Review by wild-endeavor — DISMISSED** [review]
bump if you want, can reapprove

**Review by wild-endeavor — APPROVED** [review]

**Comment by akhurana001** [comment]
> 3.8

Yes, at some point, we would remove support for 2.4.x . I have https://github.com/lyft/flyte/issues/483 to track changing the default to 3.0 , targeting end of Q4 for that.

**Pull request merged**
