### PR TITLE
Archive and activate project

### PR DESCRIPTION
**Pull request by honnix**
# TL;DR
Support archive and activate a project.

## Type
 - [ ] Bug Fix
 - [x] Feature
 - [ ] Plugin

## Are all requirements met?

 - [x] Code completed
 - [x] Smoke tested
 - [x] Unit tests added
 - [x] Code documentation added
 - [ ] Any pending items have an associated Issue

## Complete description
The client side implementation of https://github.com/lyft/flyteadmin/pull/138

## Tracking Issue
https://github.com/lyft/flyte/issues/569

## Follow-up issue
_NA_

### CODE REVIEW

**Comment by honnix** [comment]
This PR is ready for review. @wild-endeavor

**Comment by wild-endeavor** [comment]
Thanks!

**Review by wild-endeavor — APPROVED** [review]

**Comment by honnix** [comment]
Not so sure why this failed master build. Looking at it.

**Comment by honnix** [comment]
OK I see thishttps://github.com/lyft/flytekit/pull/249

**Pull request merged**
