### PR TITLE
Fast register in new flytekit

### PR DESCRIPTION
**Pull request by katrogan**
Also fix bug with register refactor where workflow template nodes weren't properly having project/domain/version substituted.

https://github.com/lyft/flyte/issues/605

### CODE REVIEW

**Comment by katrogan** [comment]
@wild-endeavor @kumare3

**Comment by wild-endeavor** [comment]
https://flyte-org.slack.com/archives/CREL4QVAQ/p1609272942221400 for more info.

**Review by wild-endeavor — APPROVED** [review]
you've tested end to end?

**Comment by katrogan** [comment]
@wild-endeavor yes. i'll add an example to flytesnacks next

**Pull request merged**
